### ISSUE TITLE
Chocolatey and KDiff3

### ISSUE THREAD

**Issue by DarkTl** [gitextensions/GitExtensionsDoc#129]
https://github.com/gitextensions/gitextensions/wiki/Application-Dependencies#git
This article recommends users to use Chocolatey to update KDiff3. Meanwhile the KDiff3 package available there is from 2015, and terribly outdated. I'm not really sure what prevented you from using direct official link (https://download.kde.org/stable/kdiff3/) instead of advertising low quality package managers.

**Comment by gerhardol** [comment]
Choco is not updated yet as there are still features missing in the updated builds where the major feature seem to be an updated Qt version. That is a good start for a neglected tool though.
But we can add the link to the newer versions too.
