### ISSUE TITLE
Manual link moved

### ISSUE THREAD

**Issue by p2s** [gitextensions/GitExtensionsDoc#131]
The link to the documentation is bad on several pages, it points to https://git-extensions-documentation.readthedocs.io/en/latest/ which returns a 404 error. Modifying it for https://git-extensions-documentation.readthedocs.io/ would be enough to point to the latest version. 

I have seen the wrong link on the following pages: 
- at the top of http://gitextensions.github.io/
- in Useful links in the readme of https://github.com/gitextensions/gitextensions#useful-links

Thanks for the great work !

**Comment by pmiossec** [comment]
Do you think you could do a PR? 

> Thanks for the great work !

Tanks for the great work to come! 😁

**Comment by p2s** [comment]
Yep I can, but not today ;) 
And I'm not sure I will be able on http://gitextensions.github.io/

**Comment by gerhardol** [comment]
latest/ was really intended for the latest development version, not the default version
master/ is used for this now
There are links in the application too

I tried to add a redirect, does not seem to have an effect
We could restore the latest branch too, at least temporary.

**Comment by gerhardol** [comment]
I resorted to rebuild the documentation with a latest branch (as well as adding release-3.5 builds, also hidden)

PRs for both this repo, the app repo and gitextensions.github.io

Improvements of the contents are very welcome.
@p2s You can see the link to the GitHub pages repo too...
