### ISSUE TITLE
Incorrect "latest" version resolution

### ISSUE THREAD

**Issue by RussKie** [gitextensions/GitExtensionsDoc#133]
### Current:
https://git-extensions-documentation.readthedocs.io/ resolves to https://git-extensions-documentation.readthedocs.io/en/release-3.4/. 
However https://git-extensions-documentation.readthedocs.io/en/latest/ resolves to https://git-extensions-documentation.readthedocs.io/en/release-3.3/
![image](https://user-images.githubusercontent.com/4403806/110274414-dffbda00-8022-11eb-83a0-063d9efad3cf.png)

### Expected:
However https://git-extensions-documentation.readthedocs.io/en/latest/ resolves to the current latest version.

**Comment by gerhardol** [comment]
The "latest" branch was already pointing to the 3.5 branch, latest build there too.
Anyway I rebuilt the branch and now latest point to 3.5

I tried to use a redirect for latest but was not able to some time ago.

**Comment by RussKie** [comment]
Thank you
