### ISSUE TITLE
Unable to install "GitExtensions" in Red Hat Enterprise Linux Server release 7.9 (Maipo)

### ISSUE THREAD

**Issue by Pankajprakashj** [gitextensions/GitExtensionsDoc#135]
Hi Team,

I am unable to install "GitExtensions - v3.5.1" in Red Hat Enterprise Linux Server release 7.9 (Maipo)
Kindly help me on the same.

Thanks & Regards
Pankaj Jadhav

**Comment by pmiossec** [comment]
There is no question in your issue so it is difficult to help.

The last version officially supported is the old v2.5x: https://github.com/gitextensions/gitextensions#version-25x

but have a look at this issue where someone successfully installed a more recent version:
https://github.com/gitextensions/gitextensions/issues/6051

No guarantee it will work.
