### ISSUE TITLE
"Download Open Office dictionaries" link is broken

### ISSUE THREAD

**Issue by adamshakhabov** [gitextensions/GitExtensionsDoc#137]
Page [Spelling](https://github.com/gitextensions/gitextensions/wiki/Spelling) -> link ["Download Open Office dictionaries"](http://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/) is broken:

![image](https://user-images.githubusercontent.com/5969304/145351070-acaa46b6-fad9-441e-ba4c-e6e0225160a0.png)

**Comment by gerhardol** [comment]
Updated the link, added LibreOffice.
(Have not tested the formats or that the netspell version is working.)
