### ISSUE TITLE
User guide for Korean newbies

### ISSUE THREAD

**Issue by semihumanbeing** [gitextensions/GitExtensionsDoc#142]
Hello, This is a Korean user of your application.
Since i started to use Git I learned to use Git Extensions. It was really helpful!
I wanted to teach my classmates how to use Git Extensions since they didn't know about version control systems. 
So I made myself a documentation about how to clone, commit and push with Git Extensions and taught my classmates with it.
and I thought it might be helpful for Korean users who just started using Git Extensions.
So I'm sharing my doc link here. thank you!

https://semihumanbeing.oopy.io/d61d2ba6-b484-442c-93c0-48e3d88aba63

**Comment by gerhardol** [comment]
You should be able to see the Korean contents by setting the encoding

The Doc repo is not translated right now and this is just a subset, so this may be a link in the wiki or so.

**Comment by RussKie** [comment]
This is great, thank you for sharing.

**Comment by drewnoakes** [comment]
감사합니다
