### ISSUE TITLE
I don't see simplified Chinese in the Settings

### ISSUE THREAD

**Issue by bingtanghulu123** [gitextensions/GitExtensionsDoc#145]
I sea documentation have simplified Chinese
![image](https://user-images.githubusercontent.com/73873790/204180875-dd462039-87fd-4776-91d5-91d35ff19b36.png)
but I don't see it in the Settings
![image](https://user-images.githubusercontent.com/73873790/204180948-c6d5b0fa-cbdb-4a9d-8921-0994930ef4c0.png)

**Comment by bingtanghulu123** [comment]
I found a solution
You can go under this ip
https://github.com/gitextensions/gitextensions/tree/master/GitUI/Translation
![image](https://user-images.githubusercontent.com/73873790/204183444-570a5e69-7145-457c-8449-a63f8344ebef.png)
Find the language you want
Download it
Put it in the installation directory
![image](https://user-images.githubusercontent.com/73873790/204183603-09ec78cb-4451-47ad-aeca-f4793ee0e023.png)

**Comment by RussKie** [comment]
We only ship translations at 95% or above. The Chinese translations weren't at that level when v4.0 was assembled.
