### ISSUE TITLE
Installation (Mac) update

### ISSUE THREAD

**Issue by spdr870** [gitextensions/GitExtensionsDoc#38]
I installed Git Extensions on osx using the information in the manual. I needed to take a few extra steps before the application was able to start and I could scroll through the history. There are still some stability issues (I am not able to commit at the moment).

I think it is nice to add these extra steps tot the installation (mac) section of the manual:

Before step 1: install git from http://git-scm/download/mac
After step 7: If you gitextensions crashes with and exception that a font is missing (generic sans serif), you probably can fix this by installing xquartz. This is a version of the X.Org X Windows System that runs on OS X. I am not sure what the side effects are. This can be installed from here: http://xquartz.macosforge.org/landing/
After step 7(2): If gitextensions still crashes because it is unable to load a plugin, empty the plugins folder.

I didn't add this info to the manual myself because I have very little experience on osx. Maybe someone can review this information.

**Comment by gerhardol** [comment]
Closing, mono is not supported in 3.x
The documentation could always be improved for 2.x, but a more specific issue should be opened.
