### ISSUE TITLE
Multilingual?

### ISSUE THREAD

**Issue by odie2** [gitextensions/GitExtensionsDoc#65]
Hello,

Is multilingual possible?

Would translate it to Polish, to complete full Polish Git Extensions' localization. It would be nice way to spread git around Poles.

Greetings

**Comment by KindDragon** [comment]
Hi.

First step done https://www.transifex.com/projects/p/git-extensions-manual/, but I don't know how publish translation ATM :-)

**Comment by odie2** [comment]
Is it possible to create glossary page in Documentation like [Transifex's](https://www.transifex.com/projects/p/git-extensions/glossary/l/pl/)?

It would be useful for non-English languages to find source English operation's name if user would search for more about this.

**Comment by odie2** [comment]
> but I don't know how to publish translation ATM :-)

Check: [Internationalization](https://docs.readthedocs.org/en/latest/i18n.html)

**Comment by KindDragon** [comment]
> s it possible to create glossary page in Documentation like Transifex's?

it's already exist https://www.transifex.com/projects/p/git-extensions-manual/glossary/l/pl/

> Check: Internationalization

I know. I only found way though creating manual repository fork https://docs.readthedocs.org/en/latest/localization.html#project-with-multiple-translations

**Comment by jbialobr** [comment]
I doubt there is such a need, nowadays everyone knows English, especially in IT.

**Comment by odie2** [comment]
> it's already exist https://www.transifex.com/projects/p/git-extensions-manual/glossary/l/pl/

I mean move those phrases to https://git-extensions-documentation.readthedocs.org/en/latest/

> So if you create fork and setup readthedocs project with polish translation we can add it to our RTD project as subproject

Will check later

@jbialobr No exactly. I know many growing programmers who although know English, Git's "slang" makes them headache.
Also programs becomes localization-able to use beautiful of every language and point to more people, who should understand it easier than after long time of work with it.
Additionaly, take a look that earlier or later, someone will do it for learn completely "greens", even in business, how use it to get less works himself. So better is do it before and professionally.
So as Git Extensions is fully Polish supporting, there should be also full manual to even more describe functions.

For curiosity: I already learned three folks how use Git basic with Git Extensions in Polish and I saved much work, so I could more programming or translating. If someday they would get know more about it, even with poor English skills, they just will be able to read brief note about it in manual.

**Comment by jbialobr** [comment]
>> I know many growing programmers who although know English, Git's "slang" makes them headache.

Here is a room for improvement and here we should direct our effort towards: to eliminate 
complexity, use a simple, easy to understand language and add more examples.

My opinion stems from my point of view about how we should learn a foreign language.
We should surround ourselves with that language as much as possible.

I don't mind creating a translation of manual, but you should note that the current version of manual is stale and uncompleted. It would be better to put in the effort to make it completed and up-to-date.

**Comment by odie2** [comment]
> It would be better to put in the effort to make it completed and up-to-date.

I don't like creating documentations and prefer programming and translating only.
KindDragon is also freelancer that does what he want at the moment. What he prefers, I don't know.

I saw that documentation is little outdated, but there are no problem to translate it and then update on Transifex with little changes. Most of description doesn't need updates or eventually, could be just expanded.

> We should surround ourselves with that language as much as possible.

Yes, but it also depens on person. There are two main groups: people who learn foreign language very easy and second group, where people have hardness in even basic grammar or even words.
I sometimes plays games or reading articles in English, but when larger story or with specialistic vocabulary, I just scrolling down text for keywords due time limit or that I am poor psychical state to read foreign language intuitively as native.

No one said that you couldn't just switch back to English.
Also, for people who are "eyes-mind" and worked with foreign UI before, it's the best way to learn when just switch to native language. They (including me) just remember what where in "that place" and pairing it and here we are - earned excellent knowledge.

**Comment by KindDragon** [comment]
> I mean move those phrases to https://git-extensions-documentation.readthedocs.org/en/latest/

We accept pull requests :-)

**Comment by gerhardol** [comment]
Closing old issues
The documentation need to be updated, then translations could be reconsidered
