### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by vbjay** [gitextensions/GitExtensionsDoc#82]
![image](https://user-images.githubusercontent.com/3629489/46035786-ec4d8000-c0d1-11e8-9f58-ee26e8f9bf10.png)
Released version is 2.51.05 and 3.0 is coming.

**Comment by gerhardol** [comment]
The 2.51.05 is seen by default by setting latest branch on the on the commit to be seen and is one of many steps involved in a release that supposedly is easy to miss.

**Comment by gerhardol** [comment]
@RussKie Can you force push so master/latest, release/2.51 is on one of the branches before updating in main repo?

**Comment by RussKie** [comment]
I'm confused and no idea what you're talking about, sorry. 😴 
You should have all necessary permissions to do it yourself 😉

**Comment by gerhardol** [comment]
I messed up and master etc are on separate commits. do not have permission to push to protected branches at all so I cannot fix. 

@russkie
The intention was to give you less work, not more...

**Comment by RussKie** [comment]
🤣 no worries

so you want `master` `latest` to point to the same commit?

![image](https://user-images.githubusercontent.com/4403806/46046469-865e0880-c164-11e8-8210-c2c7b769f965.png)

**Comment by gerhardol** [comment]
As well as release/2.51

**Comment by RussKie** [comment]
Done
![image](https://user-images.githubusercontent.com/4403806/46062948-a4505b00-c1ae-11e8-84fb-f73dc1270c67.png)
