### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/GitExtensionsDoc#95]
Some suggested changes to the documentation:

 * [ ] Consistently "Git Extensions" -> "GitExtensions"
 * [ ] Use American English instead of British English

General changes in https://github.com/gitextensions/gitextensions/issues/5921

**Comment by drewnoakes** [comment]
> Consistently "Git Extensions" -> "GitExtensions"

If so we should update the application itself:

![image](https://user-images.githubusercontent.com/350947/50663991-79428800-0fa3-11e9-9ef5-184a4167d3a8.png)


> Use American English instead of British English

Couldn't you at least wait until after March 29? 😆...😭

**Comment by RussKie** [comment]
Mwuhaha.

How about Aussie English? 😁

**Comment by gerhardol** [comment]
> If so we should update the application itself:

Separated in some places, one word in most usages from what I recall

> Couldn't you at least wait until after March 29? 

What? Will UK join US directly after leaving EU?

> How about Aussie English?

I can suggest Canadian English too. (Should be similar to aussie, but not "mate", add "ehh" in the end of sentences.)
 I studied BE in school but has written mostly AE since (also in Canada). Most documentation is in AE.

**Comment by drewnoakes** [comment]
> Will UK join US directly after leaving EU?

At this point it seems anything is possible...

> I studied BE in school but has written mostly AE since (also in Canada). Most documentation is in AE.

Yeah, it's the prevalent form online. The BCL is in AE and I don't like mixing both in code, though definitely have in the past.

Since joining an American company my little finger's had to learn where the z key is.

**Comment by RussKie** [comment]
'z' irks me, but I'll go with the flow...

**Comment by drewnoakes** [comment]
GitExtensionz

**Comment by oriash93** [comment]
> Consistently "Git Extensions" -> "GitExtensions"

Is there an intention to do it in the code as well?
Searching "Git Extensions" in the main repository comes up with more than a few results.

**Comment by RussKie** [comment]
The correct way is "Git Extensions".

> Is there an intention to do it in the code as well?

It would be good to fix, certainly. 
If you have time to send a PR it would be highly appreciated.

**Comment by oriash93** [comment]
> The correct way is "Git Extensions".
> 
> > Is there an intention to do it in the code as well?
> 
> It would be good to fix, certainly.
> If you have time to send a PR it would be highly appreciated.

@RussKie Oh my bad. Anyway, it's a matter of some comments and user prompts as you can see.

**Comment by gerhardol** [comment]
British English will (mostly) be kept too
