### ISSUE TITLE
Fix images in docs for getting_started

### ISSUE THREAD

**Issue by nmat** [gitextensions/GitExtensionsDoc#96]
The links under Settings:

Git must be installed prior to starting Git Extensions:
.. image:: /images/install/git_missing.png

First selection is language (depends on the installed languages):
.. image:: /images/install/language.png

Does not work. They should be:

Git must be installed prior to starting Git Extensions:

.. image:: /images/install/git_missing.png

First selection is language (depends on the installed languages):

.. image:: /images/install/language.png

With the blank line before to be able to read the images. Tested it locally and works with building the docs + images do show.

**Comment by gerhardol** [comment]
Thanks. Can you submit a PR?

**Comment by nmat** [comment]
Absolutely give me a few minutes.
